### PR TITLE
fix(secandperf): added rel attribute to externals links

### PR DESCRIPTION
**Pull request by mfranzke**
Add `rel="noopener"` or `rel="noreferrer"` to any external links with the attribute `target="_blank"` to improve performance and prevent security vulnerabilities. [Learn more](https://web.dev/external-anchors-use-rel-noopener?utm_source=lighthouse&utm_medium=lr).

tl;dr: External (by domain) websites being opened on links with the attribute `target="_blank" but without this `rel`-attribute may run on the same process as your page, which opens possible security problems as well as possible performance bottlenecks, even on your own page.

### CODE REVIEW

**Comment by schlomo** [comment]
I understand `noopener` and `external` but I don't understand the `noreferrer` part. Also, why not update the static links as well?

**Comment by schlomo** [comment]
Please explain the benefits of `noreferrer`or remove it. ATM I don't understand why we would benefit from that.

**Comment by mfranzke** [comment]
> Please explain the benefits of `noreferrer`or remove it. ATM I don't understand why we would benefit from that.

You're right. `noreferrer` additionally to `noopener` isn't necessary, so I've removed it. Its main target is to prevent the distribution of the referrer to the linked site, but that's most likely not relevant for your page.

**Comment by schlomo** [comment]
OK, so why not add those tags to the static links in [index.html](src/index.html)

**Comment by mfranzke** [comment]
> OK, so why not add those tags to the static links in `index.html`as well?

Sorry, missed that question previously. The problem only relates to links with the attribute `target="_blank"`, so we're fine for the index.html content, as there aren't any enhanced with this attribute within its static content.

**Comment by schlomo** [comment]
Did you see https://github.com/schlomo/chromebooks-in-deutschland/blob/master/src/chromebooks-in-deutschland.js#L400 ?

I was lazy to add `target="_blank"` to all links manually and coded it instead.

I actually want to keep my page open, which is why I added that to all links. I wasn't sure, but maybe adding `<base target="_blank">` is a better alternative. What would you suggest to achieve to goal that the page stays open when people click on external links?

**Comment by mfranzke** [comment]
> Did you see https://github.com/schlomo/chromebooks-in-deutschland/blob/master/src/chromebooks-in-deutschland.js#L400 ?
> 
> I was lazy to add `target="_blank"` to all links manually and coded it instead.
> 
> I actually want to keep my page open, which is why I added that to all links. I wasn't sure, but maybe adding `<base target="_blank">` is a better alternative. What would you suggest to achieve to goal that the page stays open when people click on external links?

Got it. I've recognized this aspect and reflected it within my change with the file https://github.com/mfranzke/chromebooks-in-deutschland/blob/fix-unsafe-externals-hyperlinks/src/chromebooks-in-deutschland.js#L403 as well.

Personally I couldn't think of any better possibility to provide a hint to the browser to open those pages in a new tab, so we should be fine with this.

**Comment by schlomo** [comment]
Thanks!

**Pull request merged**
